apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
spec:
  rules:
  - host: merciboi.link
    http:
      paths:
      - pathType: Prefix
        path: /tesla
        backend:
          service:
            name: appsvc
            port:
              number: 80
